# Tema 1.1 $\quad$ Descarga de datos

En este primer notebook vamos a recordar cómo descargar los datos para poder trabajar con ellos.

Utilizaremos Yahoo Finance.

Importamos las librerías base.

In [ ]:
!pip install yfinance==0.2.40

In [15]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.simplefilter(action="ignore", category=FutureWarning)

## 1. Descargar datos de Yahoo Finance

`yfinance` es una librería de Python que proporciona una interfaz sencilla para acceder y descargar datos financieros de Yahoo Finance. Esta biblioteca facilita la obtención de información detallada sobre precios históricos, datos de acciones, divisas, bonos, índices, etc. Esta librería es directamente compatible con `pandas`, ya que devuelve los datos en formato DataFrame.

Podéis ver la información sobre la librería en [yfinance](https://pypi.org/project/yfinance/)

Para instalar la libería si fuese necesario:

```pip install yfinance```

In [16]:
import yfinance as yf

In [17]:
# Descargamos los datos de Apple ('AAPL') entre los años 2000 y 2010

data_yahoo = yf.download(
    "AAPL", start="2000-01-01", end="2011-01-01"  # Se indica con el argumento 'start' una fecha de incio (incluida)
)  # Se indica con el argumento 'end' una fecha fin (excluida)

[*********************100%%**********************]  1 of 1 completed

La variable `data_yahoo` es un DataFrame de Pandas con la siguiente información:

* Como índice del DataFrame, **Date**: La fecha a la que se recoge la información
* **Open**: Precio de apertura del activo
* **High**: Precio máximo alcanzado por el activo
* **Low**: Precio mínimo alcanzado por el activo
* **Close**: Precio de cierre del activo
* **Adj Close**: Precio de cierre ajustado por eventos corporativos, como dividendos, splits, etc.
* **Volume**: Valor de las transacciones negociadas

Veamos el aspecto que tiene:

In [19]:
data_yahoo

                 Open       High        Low      Close  Adj Close     Volume
Date
2000-01-03   0.936384   1.004464   0.907924   0.999442   0.843077  535796800
2000-01-04   0.966518   0.987723   0.903460   0.915179   0.771997  512377600
2000-01-05   0.926339   0.987165   0.919643   0.928571   0.783294  778321600
2000-01-06   0.947545   0.955357   0.848214   0.848214   0.715508  767972800
2000-01-07   0.861607   0.901786   0.852679   0.888393   0.749402  460734400
...               ...        ...        ...        ...        ...        ...
2010-12-27  11.530357  11.622857  11.482857  11.595714   9.781531  249816000
2010-12-28  11.639643  11.666429  11.609286  11.623929   9.805331  175924000
2010-12-29  11.650714  11.658929  11.610714  11.617500   9.799908  163139200
2010-12-30  11.624286  11.625357  11.537500  11.559286   9.750806  157494400
2010-12-31  11.533929  11.552857  11.475357  11.520000   9.717662  193508000

[2767 rows x 6 columns]

In [20]:
data_yahoo.shape  # 2767 filas, 6 columnas

(2767, 6)

Lo más común es trabajar con los precios de cierre. Concretamente, vamos a seleccionar la columna de precios ajustados `Adj Close`.

**OBSERVACIÓN:** Hay que tener cuidado con las transformaciones que hacemos sobre el DataFrame. Ojo si lo que seleccionamos es un DataFrame o una Serie.

In [27]:
# Si elijo una sola columna, me devuelve una serie
serie_yahoo = data_yahoo.loc[:, "Adj Close"]

print(serie_yahoo)
print(type(serie_yahoo))

Date
2000-01-03    0.843077
2000-01-04    0.771997
2000-01-05    0.783294
2000-01-06    0.715508
2000-01-07    0.749402
                ...
2010-12-27    9.781531
2010-12-28    9.805331
2010-12-29    9.799908
2010-12-30    9.750806
2010-12-31    9.717662
Name: Adj Close, Length: 2767, dtype: float64
<class 'pandas.core.series.Series'>

In [28]:
# Si elijo una lista de columnas (aunque solo haya una), me devuelve un dataframe con una sola columna
df1_yahoo = data_yahoo.loc[:, ["Adj Close"]]

print(df1_yahoo)
print(type(df1_yahoo))

            Adj Close
Date
2000-01-03   0.843077
2000-01-04   0.771997
2000-01-05   0.783294
2000-01-06   0.715508
2000-01-07   0.749402
...               ...
2010-12-27   9.781531
2010-12-28   9.805331
2010-12-29   9.799908
2010-12-30   9.750806
2010-12-31   9.717662

[2767 rows x 1 columns]
<class 'pandas.core.frame.DataFrame'>

En la celda a continuación, descargamos los datos de varios activos financieros a la vez. Simplemente pasamos a `yf.download` una lista de activos en lugar de solo uno:

In [29]:
activos = ["AAPL", "MSFT", "AMZN", "GOOG", "TSLA", "NVDA", "ADBE", "NFLX"]
df_yahoo = yf.download(activos, start="2000-01-01", end="2011-01-01")

[*********************100%%**********************]  8 of 8 completed

En este caso, al descargar una lista de activos, yfinance nos devuelve un DataFrame multinivel en las columnas `(atributo, activo)`, donde el primer nivel representa los atributos (open, high, low, close, etc.) y el segundo nivel el activo correspondiente (AAPL, MSFT, etc.):

In [30]:
df_yahoo

Price      Adj Close                                                        \
Ticker          AAPL       ADBE      AMZN       GOOG       MSFT       NFLX
Date
2000-01-03  0.843077  16.274677  4.468750        NaN  35.864075        NaN
2000-01-04  0.771997  14.909400  4.096875        NaN  34.652580        NaN
2000-01-05  0.783294  15.204176  3.487500        NaN  35.017956        NaN
2000-01-06  0.715508  15.328290  3.278125        NaN  33.844913        NaN
2000-01-07  0.749402  16.072987  3.478125        NaN  34.287209        NaN
...              ...        ...       ...        ...        ...        ...
2010-12-27  9.781531  30.950001  9.107000  14.949549  21.572605  25.715714
2010-12-28  9.805331  30.920000  9.054500  14.863680  21.526491  26.238571
2010-12-29  9.799908  30.969999  9.168500  14.915300  21.495752  25.752857
2010-12-30  9.750806  30.570000  9.137500  14.862192  21.403521  25.685715
2010-12-31  9.717662  30.780001  9.000000  14.740834  21.449646  25.100000

Price                               Close             ...      Open            \
Ticker          NVDA      TSLA       AAPL       ADBE  ...      NVDA      TSLA
Date                                                  ...
2000-01-03  0.089440       NaN   0.999442  16.390625  ...  0.098438       NaN
2000-01-04  0.087052       NaN   0.915179  15.015625  ...  0.095833       NaN
2000-01-05  0.084186       NaN   0.928571  15.312500  ...  0.092188       NaN
2000-01-06  0.078692       NaN   0.848214  15.437500  ...  0.091797       NaN
2000-01-07  0.080007       NaN   0.888393  16.187500  ...  0.085417       NaN
...              ...       ...        ...        ...  ...       ...       ...
2010-12-27  0.343907  1.703333  11.595714  30.950001  ...  0.372000  1.868000
2010-12-28  0.342531  1.760667  11.623929  30.920000  ...  0.375000  1.723333
2010-12-29  0.342531  1.848667  11.617500  30.969999  ...  0.373250  1.802000
2010-12-30  0.343678  1.766667  11.559286  30.570000  ...  0.373000  1.846667
2010-12-31  0.353078  1.775333  11.520000  30.780001  ...  0.375000  1.771333

Price          Volume                                                         \
Ticker           AAPL      ADBE       AMZN        GOOG      MSFT        NFLX
Date
2000-01-03  535796800   7384400  322352000         NaN  53228400         NaN
2000-01-04  512377600   7813200  349748000         NaN  54119000         NaN
2000-01-05  778321600  14927200  769148000         NaN  64059600         NaN
2000-01-06  767972800  10221200  375040000         NaN  54976600         NaN
2000-01-07  460734400   8253200  210108000         NaN  62013600         NaN
...               ...       ...        ...         ...       ...         ...
2010-12-27  249816000   2920300   44988000  48505130.0  21652800  26189100.0
2010-12-28  175924000   3748400   39500000  42751645.0  23042200  27215300.0
2010-12-29  163139200   2662600   62402000  40920808.0  19502500  19399100.0
2010-12-30  157494400   3435500   39224000  39728356.0  20786100  14743400.0
2010-12-31  193508000   2841300   69038000  61802787.0  24752000  21562800.0

Price
Ticker           NVDA         TSLA
Date
2000-01-03  300912000          NaN
2000-01-04  300480000          NaN
2000-01-05  188352000          NaN
2000-01-06  120480000          NaN
2000-01-07   71184000          NaN
...               ...          ...
2010-12-27  255500000  139528500.0
2010-12-28  194260000   60844500.0
2010-12-29  177660000   49788000.0
2010-12-30  174488000   30616500.0
2010-12-31  391252000   21268500.0

[2767 rows x 48 columns]

Pongamos las tres situaciones posibles como ejercicio:

1. Del DataFrame descargado, muestra el `Open` de todos los activos.
2. Del DataFrame descargado, muestra el `Close` de `'MSFT'`.
3. Del DataFrame descargado, muestra todos los atributos de `'NVDA'`.

In [31]:
# 1. Del DataFrame descargado, muestra el `Open` de todos los activos.

# SOLUCION
solucion_1 = df_yahoo.loc[:, "Open"]
solucion_1.head()

Ticker,AAPL,ADBE,AMZN,GOOG,MSFT,NFLX,NVDA,TSLA
Date,,,,,,,,
2000-01-03,0.936384,16.812500,4.075000,NaN,58.68750,NaN,0.098438,NaN
2000-01-04,0.966518,15.750000,4.268750,NaN,56.78125,NaN,0.095833,NaN
2000-01-05,0.926339,14.562500,3.525000,NaN,55.56250,NaN,0.092188,NaN
2000-01-06,0.947545,15.359375,3.565625,NaN,56.09375,NaN,0.091797,NaN
2000-01-07,0.861607,15.390625,3.350000,NaN,54.31250,NaN,0.085417,NaN

In [32]:
# 2. Del DataFrame descargado, muestra el `Close` de 'MSFT'.

# SOLUCION
idx = pd.IndexSlice
solucion_2 = df_yahoo.loc[:, idx["Close", "MSFT"]]
solucion_2.head()

Date
2000-01-03    58.28125
2000-01-04    56.31250
2000-01-05    56.90625
2000-01-06    55.00000
2000-01-07    55.71875
Name: (Close, MSFT), dtype: float64

In [33]:
# 3. Del DataFrame descargado, muestra todos los atributos de 'NVDA'.

# SOLUCION
idx = pd.IndexSlice
solucion_3 = df_yahoo.loc[:, idx[:, "NVDA"]]
solucion_3.columns = solucion_3.columns.droplevel(1)  # Prueba a comentar esta línea. ¿Qué sucede?
solucion_3.head()

Price       Adj Close     Close      High       Low      Open     Volume
Date
2000-01-03   0.089440  0.097526  0.099219  0.091927  0.098438  300912000
2000-01-04   0.087052  0.094922  0.096094  0.090104  0.095833  300480000
2000-01-05   0.084186  0.091797  0.093750  0.090495  0.092188  188352000
2000-01-06   0.078692  0.085807  0.091797  0.082292  0.091797  120480000
2000-01-07   0.080007  0.087240  0.088151  0.084115  0.085417   71184000