# Topic 1.1 $\quad$ Data Download

In this first notebook, we will review how to download financial data so that we can work with it.

We will use Yahoo Finance.

Import the main libraries.

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

warnings.simplefilter(action="ignore", category=FutureWarning)

## 1. Download data from Yahoo Finance

`yfinance` is a Python library that provides a simple interface for accessing and downloading financial data from Yahoo Finance. It makes it easy to obtain historical prices and information on stocks, currencies, bonds, indices, and other financial assets.

The library integrates naturally with `pandas`, since downloaded data are returned as a DataFrame.

You can find more information about the library here: [yfinance](https://pypi.org/project/yfinance/)

Install the library if necessary:

```python
pip install yfinance
```

In [ ]:
import yfinance as yf

In [ ]:
# Download Apple ('AAPL') data between 2000 and 2010

data_yahoo = yf.download(
    "AAPL",
    start="2000-01-01",         # 'start' specifies the initial date (included)
    end="2011-01-01",           # 'end' specifies the final date (excluded)
    auto_adjust=False,          # False returns 'Close' and 'Adj Close' separately. True makes Close = Adj Close
    multi_level_index=False,    # We do not want a MultiIndex in this case
)

[*********************100%***********************]  1 of 1 completed

The variable `data_yahoo` is a Pandas DataFrame containing the following information:

* **Date** (DataFrame index): date corresponding to each observation
* **Open**: opening price of the asset
* **High**: highest price reached during the period
* **Low**: lowest price reached during the period
* **Close**: closing price of the asset
* **Adj Close**: closing price adjusted for corporate events such as dividends and stock splits
* **Volume**: trading volume

Let's take a look at the DataFrame:

In [ ]:
data_yahoo

            Adj Close      Close       High        Low       Open     Volume
Date
2000-01-03   0.837002   0.999442   1.004464   0.907924   0.936384  535796800
2000-01-04   0.766435   0.915179   0.987723   0.903460   0.966518  512377600
2000-01-05   0.777650   0.928571   0.987165   0.919643   0.926339  778321600
2000-01-06   0.710353   0.848214   0.955357   0.848214   0.947545  767972800
2000-01-07   0.744002   0.888393   0.901786   0.852679   0.861607  460734400
...               ...        ...        ...        ...        ...        ...
2010-12-27   9.711055  11.595714  11.622857  11.482857  11.530357  249816000
2010-12-28   9.734686  11.623929  11.666429  11.609286  11.639643  175924000
2010-12-29   9.729302  11.617500  11.658929  11.610714  11.650714  163139200
2010-12-30   9.680549  11.559286  11.625357  11.537500  11.624286  157494400
2010-12-31   9.647651  11.520000  11.552857  11.475357  11.533929  193508000

[2767 rows x 6 columns]

In [ ]:
data_yahoo.shape  # 2767 rows, 6 columns

(2767, 6)

We will usually work with closing prices. In particular, we are going to select the adjusted closing price column, `Adj Close`.

**NOTE:** Be careful when selecting data from a DataFrame. Depending on how the selection is made, the result may be either a Pandas Series or a DataFrame.

In [ ]:
# Selecting a single column returns a Series
serie_yahoo = data_yahoo.loc[:, "Adj Close"]

print(serie_yahoo)
print(type(serie_yahoo))

Date
2000-01-03    0.837002
2000-01-04    0.766435
2000-01-05    0.777650
2000-01-06    0.710353
2000-01-07    0.744002
                ...
2010-12-27    9.711055
2010-12-28    9.734686
2010-12-29    9.729302
2010-12-30    9.680549
2010-12-31    9.647651
Name: Adj Close, Length: 2767, dtype: float64
<class 'pandas.core.series.Series'>

In [ ]:
# Selecting a list of columns (even if it contains only one column)
# returns a DataFrame
df1_yahoo = data_yahoo.loc[:, ["Adj Close"]]

print(df1_yahoo)
print(type(df1_yahoo))

            Adj Close
Date
2000-01-03   0.837002
2000-01-04   0.766435
2000-01-05   0.777650
2000-01-06   0.710353
2000-01-07   0.744002
...               ...
2010-12-27   9.711055
2010-12-28   9.734686
2010-12-29   9.729302
2010-12-30   9.680549
2010-12-31   9.647651

[2767 rows x 1 columns]
<class 'pandas.core.frame.DataFrame'>

In the next cell, we download data for several financial assets at the same time. We simply pass a list of tickers to `yf.download` instead of a single ticker:

In [ ]:
activos = ["AAPL", "MSFT", "AMZN", "GOOG", "TSLA", "NVDA", "ADBE", "NFLX"]
df_yahoo = yf.download(
    activos,
    start="2000-01-01",
    end="2011-01-01",
    auto_adjust=False,
    multi_level_index=True,
)

[*********************100%***********************]  8 of 8 completed

When we download several assets, `yfinance` returns a DataFrame with **MultiIndex columns** of the form `(attribute, asset)`.

The first level contains the attributes (`Open`, `High`, `Low`, `Close`, etc.) and the second level identifies the corresponding asset (`AAPL`, `MSFT`, etc.).

In [ ]:
df_yahoo

Price      Adj Close                                                       \
Ticker          AAPL       ADBE      AMZN       GOOG       MSFT      NFLX
Date
2000-01-03  0.837002  16.274670  4.468750        NaN  35.377014       NaN
2000-01-04  0.766435  14.909400  4.096875        NaN  34.181965       NaN
2000-01-05  0.777650  15.204172  3.487500        NaN  34.542366       NaN
2000-01-06  0.710353  15.328290  3.278125        NaN  33.385277       NaN
2000-01-07  0.744002  16.072985  3.478125        NaN  33.821556       NaN
...              ...        ...       ...        ...        ...       ...
2010-12-27  9.711055  30.950001  9.107000  14.862492  21.279627  2.571571
2010-12-28  9.734686  30.920000  9.054500  14.777123  21.234150  2.623857
2010-12-29  9.729302  30.969999  9.168500  14.828445  21.203827  2.575286
2010-12-30  9.680549  30.570000  9.137500  14.775644  21.112852  2.568571
2010-12-31  9.647651  30.780001  9.000000  14.654992  21.158333  2.510000

Price                               Close             ...      Open            \
Ticker          NVDA      TSLA       AAPL       ADBE  ...      NVDA      TSLA
Date                                                  ...
2000-01-03  0.089206       NaN   0.999442  16.390625  ...  0.098438       NaN
2000-01-04  0.086825       NaN   0.915179  15.015625  ...  0.095833       NaN
2000-01-05  0.083966       NaN   0.928571  15.312500  ...  0.092188       NaN
2000-01-06  0.078487       NaN   0.848214  15.437500  ...  0.091797       NaN
2000-01-07  0.079798       NaN   0.888393  16.187500  ...  0.085417       NaN
...              ...       ...        ...        ...  ...       ...       ...
2010-12-27  0.343010  1.703333  11.595714  30.950001  ...  0.372000  1.868000
2010-12-28  0.341638  1.760667  11.623929  30.920000  ...  0.375000  1.723333
2010-12-29  0.341638  1.848667  11.617500  30.969999  ...  0.373250  1.802000
2010-12-30  0.342782  1.766667  11.559286  30.570000  ...  0.373000  1.846667
2010-12-31  0.352157  1.775333  11.520000  30.780001  ...  0.375000  1.771333

Price          Volume                                                          \
Ticker           AAPL      ADBE       AMZN        GOOG      MSFT         NFLX
Date
2000-01-03  535796800   7384400  322352000         NaN  53228400          NaN
2000-01-04  512377600   7813200  349748000         NaN  54119000          NaN
2000-01-05  778321600  14927200  769148000         NaN  64059600          NaN
2000-01-06  767972800  10221200  375040000         NaN  54976600          NaN
2000-01-07  460734400   8253200  210108000         NaN  62013600          NaN
...               ...       ...        ...         ...       ...          ...
2010-12-27  249816000   2920300   44988000  48505130.0  21652800  261891000.0
2010-12-28  175924000   3748400   39500000  42751645.0  23042200  272153000.0
2010-12-29  163139200   2662600   62402000  40920808.0  19502500  193991000.0
2010-12-30  157494400   3435500   39224000  39728356.0  20786100  147434000.0
2010-12-31  193508000   2841300   69038000  61802787.0  24752000  215628000.0

Price
Ticker           NVDA         TSLA
Date
2000-01-03  300912000          NaN
2000-01-04  300480000          NaN
2000-01-05  188352000          NaN
2000-01-06  120480000          NaN
2000-01-07   71184000          NaN
...               ...          ...
2010-12-27  255500000  139528500.0
2010-12-28  194260000   60844500.0
2010-12-29  177660000   49788000.0
2010-12-30  174488000   30616500.0
2010-12-31  391252000   21268500.0

[2767 rows x 48 columns]

Let's practice the three most common selection cases:

1. From the downloaded DataFrame, display the `Open` prices for all assets.
2. Display the `Close` prices for `MSFT`.
3. Display all available attributes for `NVDA`.

In [ ]:
# 1. Display the `Open` prices for all assets.

# SOLUTION
solucion_1 = df_yahoo.loc[:, "Open"]
solucion_1.head()

Ticker,AAPL,ADBE,AMZN,GOOG,MSFT,NFLX,NVDA,TSLA
Date,,,,,,,,
2000-01-03,0.936384,16.812500,4.075000,NaN,58.68750,NaN,0.098438,NaN
2000-01-04,0.966518,15.750000,4.268750,NaN,56.78125,NaN,0.095833,NaN
2000-01-05,0.926339,14.562500,3.525000,NaN,55.56250,NaN,0.092188,NaN
2000-01-06,0.947545,15.359375,3.565625,NaN,56.09375,NaN,0.091797,NaN
2000-01-07,0.861607,15.390625,3.350000,NaN,54.31250,NaN,0.085417,NaN

In [ ]:
# 2. Display the `Close` prices for 'MSFT'.

# SOLUTION
solucion_2 = df_yahoo["Close"]["MSFT"]
solucion_2.head()

Date
2000-01-03    58.28125
2000-01-04    56.31250
2000-01-05    56.90625
2000-01-06    55.00000
2000-01-07    55.71875
Name: MSFT, dtype: float64

In [ ]:
df_yahoo

Price      Adj Close                                                       \
Ticker          AAPL       ADBE      AMZN       GOOG       MSFT      NFLX
Date
2000-01-03  0.837002  16.274670  4.468750        NaN  35.377014       NaN
2000-01-04  0.766435  14.909400  4.096875        NaN  34.181965       NaN
2000-01-05  0.777650  15.204172  3.487500        NaN  34.542366       NaN
2000-01-06  0.710353  15.328290  3.278125        NaN  33.385277       NaN
2000-01-07  0.744002  16.072985  3.478125        NaN  33.821556       NaN
...              ...        ...       ...        ...        ...       ...
2010-12-27  9.711055  30.950001  9.107000  14.862492  21.279627  2.571571
2010-12-28  9.734686  30.920000  9.054500  14.777123  21.234150  2.623857
2010-12-29  9.729302  30.969999  9.168500  14.828445  21.203827  2.575286
2010-12-30  9.680549  30.570000  9.137500  14.775644  21.112852  2.568571
2010-12-31  9.647651  30.780001  9.000000  14.654992  21.158333  2.510000

Price                               Close             ...      Open            \
Ticker          NVDA      TSLA       AAPL       ADBE  ...      NVDA      TSLA
Date                                                  ...
2000-01-03  0.089206       NaN   0.999442  16.390625  ...  0.098438       NaN
2000-01-04  0.086825       NaN   0.915179  15.015625  ...  0.095833       NaN
2000-01-05  0.083966       NaN   0.928571  15.312500  ...  0.092188       NaN
2000-01-06  0.078487       NaN   0.848214  15.437500  ...  0.091797       NaN
2000-01-07  0.079798       NaN   0.888393  16.187500  ...  0.085417       NaN
...              ...       ...        ...        ...  ...       ...       ...
2010-12-27  0.343010  1.703333  11.595714  30.950001  ...  0.372000  1.868000
2010-12-28  0.341638  1.760667  11.623929  30.920000  ...  0.375000  1.723333
2010-12-29  0.341638  1.848667  11.617500  30.969999  ...  0.373250  1.802000
2010-12-30  0.342782  1.766667  11.559286  30.570000  ...  0.373000  1.846667
2010-12-31  0.352157  1.775333  11.520000  30.780001  ...  0.375000  1.771333

Price          Volume                                                          \
Ticker           AAPL      ADBE       AMZN        GOOG      MSFT         NFLX
Date
2000-01-03  535796800   7384400  322352000         NaN  53228400          NaN
2000-01-04  512377600   7813200  349748000         NaN  54119000          NaN
2000-01-05  778321600  14927200  769148000         NaN  64059600          NaN
2000-01-06  767972800  10221200  375040000         NaN  54976600          NaN
2000-01-07  460734400   8253200  210108000         NaN  62013600          NaN
...               ...       ...        ...         ...       ...          ...
2010-12-27  249816000   2920300   44988000  48505130.0  21652800  261891000.0
2010-12-28  175924000   3748400   39500000  42751645.0  23042200  272153000.0
2010-12-29  163139200   2662600   62402000  40920808.0  19502500  193991000.0
2010-12-30  157494400   3435500   39224000  39728356.0  20786100  147434000.0
2010-12-31  193508000   2841300   69038000  61802787.0  24752000  215628000.0

Price
Ticker           NVDA         TSLA
Date
2000-01-03  300912000          NaN
2000-01-04  300480000          NaN
2000-01-05  188352000          NaN
2000-01-06  120480000          NaN
2000-01-07   71184000          NaN
...               ...          ...
2010-12-27  255500000  139528500.0
2010-12-28  194260000   60844500.0
2010-12-29  177660000   49788000.0
2010-12-30  174488000   30616500.0
2010-12-31  391252000   21268500.0

[2767 rows x 48 columns]

In [ ]:
# 3. Display all available attributes for 'NVDA'.

# SOLUTION
solucion_3 = df_yahoo.xs("NVDA", axis=1, level=1)
solucion_3.head()

Price       Adj Close     Close      High       Low      Open     Volume
Date
2000-01-03   0.089206  0.097526  0.099219  0.091927  0.098438  300912000
2000-01-04   0.086825  0.094922  0.096094  0.090104  0.095833  300480000
2000-01-05   0.083966  0.091797  0.093750  0.090495  0.092188  188352000
2000-01-06   0.078487  0.085807  0.091797  0.082292  0.091797  120480000
2000-01-07   0.079798  0.087240  0.088151  0.084115  0.085417   71184000

## 2. Practice Exercises

Try to solve the following exercises before looking at any solution.

### Exercise 1

Download daily data for `META` from **January 1, 2020** to **January 1, 2022**.

Then:

1. Display the first five rows.
2. Check the shape of the DataFrame.
3. Select the `Adj Close` column as a Pandas Series.

In [ ]:
# Exercise 1
# Write your code here
meta = yf.download(
    "META",
    start="2020-01-01",
    end="2022-01-01",
    auto_adjust=False,
    progress=False,
    multi_level_index=False
)

# 1. Display the first five rows
display(meta.head())

# 2. Check the shape: (number of rows, number of columns)
print(meta.shape)

# 3. Select Adj Close as a Pandas Series
adj_close = meta["Adj Close"]

display(adj_close.head())

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2020-01-02,207.789856,209.779999,209.789993,206.270004,206.750000,12077100
2020-01-03,206.690399,208.669998,210.399994,206.949997,207.210007,11188400
2020-01-06,210.583130,212.600006,212.779999,206.520004,206.699997,17058900
2020-01-07,211.038742,213.059998,214.580002,211.750000,212.820007,14912400
2020-01-08,213.178238,215.220001,216.240005,212.610001,213.000000,13475000

(505, 6)

Date
2020-01-02    207.789856
2020-01-03    206.690399
2020-01-06    210.583130
2020-01-07    211.038742
2020-01-08    213.178238
Name: Adj Close, dtype: float64

### Exercise 2

Using the `df_yahoo` DataFrame created above:

1. Select the `High` prices for all assets.
2. Select the `Volume` data for `AAPL`.
3. Select all attributes for `TSLA`.

In [ ]:
# Exercise 2
# Write your code here
# 1. Select High prices for all assets
high_prices = df_yahoo["High"]

# 2. Select Volume data for AAPL
aapl_volume = df_yahoo["Volume"]["AAPL"]

# 3. Select all attributes for TSLA
tsla = df_yahoo.xs("TSLA", axis=1, level=1)

# Display the results
display(high_prices.head())
display(aapl_volume.head())
display(tsla.head())

Ticker          AAPL       ADBE      AMZN  GOOG     MSFT  NFLX      NVDA  TSLA
Date
2000-01-03  1.004464  16.875000  4.478125   NaN  59.3125   NaN  0.099219   NaN
2000-01-04  0.987723  16.453125  4.575000   NaN  58.5625   NaN  0.096094   NaN
2000-01-05  0.987165  15.687500  3.756250   NaN  58.1875   NaN  0.093750   NaN
2000-01-06  0.955357  15.656250  3.634375   NaN  56.9375   NaN  0.091797   NaN
2000-01-07  0.901786  16.187500  3.525000   NaN  56.1250   NaN  0.088151   NaN

Date
2000-01-03    535796800
2000-01-04    512377600
2000-01-05    778321600
2000-01-06    767972800
2000-01-07    460734400
Name: AAPL, dtype: int64

Price       Adj Close  Close  High  Low  Open  Volume
Date
2000-01-03        NaN    NaN   NaN  NaN   NaN     NaN
2000-01-04        NaN    NaN   NaN  NaN   NaN     NaN
2000-01-05        NaN    NaN   NaN  NaN   NaN     NaN
2000-01-06        NaN    NaN   NaN  NaN   NaN     NaN
2000-01-07        NaN    NaN   NaN  NaN   NaN     NaN

### Exercise 3

Download data for the following three assets:

```python
["AAPL", "MSFT", "GOOG"]
```

for the period **January 1, 2023** to **January 1, 2024**.

Then select only the `Adj Close` prices and display the first five rows.

> **Goal:** Practice downloading several assets at once and selecting one attribute from a MultiIndex DataFrame.

In [ ]:
# Exercise 3
# Write your code here


# Download daily data for the three assets
df = yf.download(
    ["AAPL", "MSFT", "GOOG"],
    start="2023-01-01",
    end="2024-01-01",
    auto_adjust=False,
    progress=False
)

# Select only the Adjusted Close prices
adj_close = df["Adj Close"]

# Display the first five rows
adj_close.head()

Ticker            AAPL       GOOG        MSFT
Date
2023-01-03  122.876755  88.858353  232.510559
2023-01-04  124.144119  87.877655  222.339798
2023-01-05  122.827614  85.955841  215.750153
2023-01-06  127.346954  87.332825  218.292816
2023-01-09  127.867668  87.966805  220.418243